name: emcaps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python >=3.10
  - albumentations >=1.0
  - hydra-core >=1.2
  - imageio >=2.19
  - ipython >=8
  - matplotlib >=3.4
#  - magicgui >=0.5
#  - napari >=0.4.16
  - numpy >=1.22
  - omegaconf >=2.2
  - pandas >=1.4
  - pillow >=9.1
  - pyyaml >=6.0
  - scikit-image >=0.19
  - scikit-learn >=1.1
  - scipy >=1.8
  - seaborn >=0.11
  - setuptools >=62
  # - pytorch >=1.12 # [not osx]  # workaround for OMP issues: install pytorch from pip below
  - tqdm >=4.64
  - typing_extensions >=4.2

  - pip
  - pip:
    - torch >=1.12 # [osx]  # use pip version because conda version segfaults (TODO: debug)
    - git+https://github.com/ELEKTRONN/elektronn3.git@emcaps#egg=elektronn3
